# Generated by Django 5.0.6 on 2024-06-04 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Employe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=50)),
                ('prenom', models.CharField(max_length=50)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='images/employe')),
                ('poste', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
        migrations.AddField(
            model_name='managervideo',
            name='description',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='managervideo',
            name='nom_hotel',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='managervideo',
            name='quote',
            field=models.TextField(default=''),
        ),
    ]
