# Generated by Django 5.0.6 on 2024-06-04 10:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_employe_managervideo_description_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PosteEmploye',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('poste', models.CharField(max_length=50)),
            ],
        ),
        migrations.AlterField(
            model_name='employe',
            name='poste',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.posteemploye'),
        ),
    ]
