# Generated by Django 5.0.5 on 2024-06-04 13:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_posteemploye_alter_employe_poste'),
    ]

    operations = [
        migrations.AddField(
            model_name='managervideo',
            name='employe',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.employe'),
        ),
    ]
