# Generated by Django 5.0.6 on 2024-06-05 11:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_herohome'),
    ]

    operations = [
        migrations.RenameField(
            model_name='herohome',
            old_name='nom',
            new_name='titre',
        ),
    ]
