# Generated by Django 5.0.6 on 2024-06-05 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_rename_nom_herohome_titre'),
    ]

    operations = [
        migrations.RenameField(
            model_name='herohome',
            old_name='chaine',
            new_name='best',
        ),
        migrations.AddField(
            model_name='herohome',
            name='place',
            field=models.CharField(default='', max_length=50),
        ),
    ]
