# Generated by Django 5.0.6 on 2024-06-06 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_rename_chaine_herohome_best_herohome_place'),
    ]

    operations = [
        migrations.CreateModel(
            name='BanierePages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='images/hotels')),
            ],
        ),
    ]
