# Generated by Django 5.0.6 on 2024-06-06 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_footergallery'),
    ]

    operations = [
        migrations.AlterField(
            model_name='footergallery',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images/footer'),
        ),
    ]
