# Generated by Django 5.0.5 on 2024-06-10 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_faq'),
    ]

    operations = [
        migrations.AddField(
            model_name='faq',
            name='active',
            field=models.BooleanField(default=False),
        ),
    ]
