# Generated by Django 5.0.6 on 2024-06-12 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0015_faq_active'),
    ]

    operations = [
        migrations.CreateModel(
            name='Facilities',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=50)),
                ('sous_titre', models.CharField(max_length=50)),
                ('description', models.TextField(default='')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='images/facilities')),
                ('order', models.PositiveIntegerField(unique=True)),
            ],
        ),
    ]
