# Generated by Django 5.0.6 on 2024-06-17 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0016_facilities'),
    ]

    operations = [
        migrations.CreateModel(
            name='FacilitiesRoom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=50)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='images/facilitiesRoom')),
                ('image', models.ImageField(blank=True, null=True, upload_to='images/facilitiesRoom')),
            ],
        ),
    ]
