# Generated by Django 5.0.6 on 2024-06-17 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0017_facilitiesroom'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rooms',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=50)),
                ('description', models.TextField(default='')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='images/rooms')),
                ('etoiles', models.PositiveIntegerField()),
                ('lit', models.PositiveIntegerField()),
                ('nom_lit', models.CharField(max_length=50)),
                ('prix', models.PositiveIntegerField()),
                ('adultes', models.PositiveIntegerField()),
                ('enfants', models.PositiveIntegerField()),
                ('max_adultes', models.PositiveIntegerField()),
                ('max_enfants', models.PositiveIntegerField()),
                ('date_in', models.DateField()),
                ('date_out', models.DateField()),
                ('superficie', models.PositiveIntegerField()),
                ('prom_start', models.DateField()),
                ('prom_end', models.DateField()),
                ('amenities', models.ManyToManyField(blank=True, null=True, to='app.facilitiesroom')),
            ],
        ),
    ]
