# Generated by Django 5.0.6 on 2024-06-17 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0018_rooms'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rooms',
            name='amenities',
            field=models.ManyToManyField(blank=True, to='app.facilitiesroom'),
        ),
    ]
