# Generated by Django 5.0.6 on 2024-06-18 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0019_alter_rooms_amenities'),
    ]

    operations = [
        migrations.CreateModel(
            name='RoomService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=50)),
                ('image', models.ImageField(blank=True, null=True, upload_to='images/rooms')),
                ('prix', models.PositiveIntegerField()),
                ('desc1', models.CharField(max_length=80)),
                ('desc2', models.CharField(max_length=80)),
                ('desc3', models.CharField(max_length=80)),
                ('desc4', models.CharField(max_length=80)),
            ],
        ),
    ]
