# Generated by Django 5.0.6 on 2024-06-18 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0020_roomservice'),
    ]

    operations = [
        migrations.AddField(
            model_name='facilities',
            name='dress_code1',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='facilities',
            name='dress_code2',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='facilities',
            name='dress_code3',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='facilities',
            name='rules',
            field=models.TextField(default=''),
        ),
    ]
