# Generated by Django 5.0.6 on 2024-06-18 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0021_facilities_dress_code1_facilities_dress_code2_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='facilities',
            name='dress_code1',
            field=models.CharField(default='', max_length=150),
        ),
        migrations.AlterField(
            model_name='facilities',
            name='dress_code2',
            field=models.CharField(default='', max_length=150),
        ),
        migrations.AlterField(
            model_name='facilities',
            name='dress_code3',
            field=models.CharField(default='', max_length=150),
        ),
    ]
