# Generated by Django 5.0.6 on 2024-06-18 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0022_alter_facilities_dress_code1_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='rooms',
            name='pourcentage_prom',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
