# Generated by Django 5.0.6 on 2024-06-19 12:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0025_tag'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Tag',
            new_name='Tags',
        ),
    ]
