# Generated by Django 5.0.6 on 2024-06-19 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0028_blog_blogdescription_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='tags',
            field=models.ManyToManyField(blank=True, to='app.tags'),
        ),
    ]
