# Generated by Django 5.0.6 on 2024-06-26 17:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0038_alter_rooms_adultes_alter_rooms_date_in_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('adultes', models.PositiveIntegerField()),
                ('enfants', models.PositiveIntegerField()),
                ('date_in', models.DateField()),
                ('date_out', models.DateField()),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.rooms')),
            ],
        ),
    ]
